DROP TABLE IF EXISTS clientes;

CREATE TABLE clientes (
 id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 nome VARCHAR(150) NOT NULL,
 email VARCHAR(150) NOT NULL
);

INSERT INTO clientes (nome, email) VALUES
('Ana Souza', 'ana@email.com'),
('Bruno Lima', 'bruno@email.com'),
('Carla Mendes', 'carla@email.com');

INSERT INTO produtos (nome, descricao, preco, quantidade_estoque) VALUES
('Hamburguer Artesanal', 'Pao, carne, queijo e molho especial', 32.90, 10),
('Pizza Calabresa', 'Pizza media de calabresa', 49.90, 5),
('Refrigerante 2L', 'Refrigerante cola 2 litros', 12.00, 20),
('Batata Frita', 'Porcao media de batata frita', 18.50, 8);