version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: cp2-postgres
    restart: always

    environment:
      POSTGRES_DB: cp2_pedidos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: